
   // $( document ).ready(function() {

		

var json = {
    "categorie":
    {
        "pays": [
            { "name": "afghanistan" },
            { "name": "afrique du sud" },
            { "name": "albanie" },
            { "name": "algerie" },
            { "name": "allemagne" },
            { "name": "andorre" },
            { "name": "angola" },
            { "name": "anguilla" },
            { "name": "antigua-et-barbuda" },
            { "name": "antilles neerlandaises" },
            { "name": "arabie saoudite" },
            { "name": "argentine" },
            { "name": "armenie" },
            { "name": "aruba" },
            { "name": "australie" },
            { "name": "autriche" },
            { "name": "azerbaidjan" },
            { "name": "bahamas" },
            { "name": "bahrein" },
            { "name": "bangladesh" },
            { "name": "barbade" },
            { "name": "belgique" },
            { "name": "belize" },
            { "name": "benin" },
            { "name": "bermudes" },
            { "name": "bhoutan" },
            { "name": "bielorussie" },
            { "name": "birmanie (myanmar)" },
            { "name": "bolivie" },
            { "name": "bosnie-herzegovine" },
            { "name": "botswana" },
            { "name": "bresil" },
            { "name": "brunei" },
            { "name": "bulgarie" },
            { "name": "burkina faso" },
            { "name": "burundi" },
            { "name": "cambodge" },
            { "name": "cameroun" },
            { "name": "canada" },
            { "name": "cap-vert" },
            { "name": "chili" },
            { "name": "chine" },
            { "name": "chypre" },
            { "name": "colombie" },
            { "name": "comores" },
            { "name": "coree du nord" },
            { "name": "coree du sud" },
            { "name": "costa rica" },
            { "name": "cote d'ivoire" },
            { "name": "croatie" },
            { "name": "cuba" },
            { "name": "danemark" },
            { "name": "djibouti" },
            { "name": "dominique" },
            { "name": "egypte" },
            { "name": "emirats arabes unis" },
            { "name": "equateur" },
            { "name": "erythree" },
            { "name": "espagne" },
            { "name": "estonie" },
            { "name": "etats federes de micronesie" },
            { "name": "etats-unis" },
            { "name": "ethiopie" },
            { "name": "fidji" },
            { "name": "finlande" },
            { "name": "france" },
            { "name": "gabon" },
            { "name": "gambie" },
            { "name": "georgie" },
            { "name": "georgie du sud et les iles sandwich du sud" },
            { "name": "ghana" },
            { "name": "gibraltar" },
            { "name": "grece" },
            { "name": "grenade" },
            { "name": "groenland" },
            { "name": "guadeloupe" },
            { "name": "guam" },
            { "name": "guatemala" },
            { "name": "guinee" },
            { "name": "guinee-bissau" },
            { "name": "guinee equatoriale" },
            { "name": "guyana" },
            { "name": "guyane francaise" },
            { "name": "haiti" },
            { "name": "honduras" },
            { "name": "hong-kong" },
            { "name": "hongrie" },
            { "name": "ile christmas" },
            { "name": "ile de man" },
            { "name": "ile norfolk" },
            { "name": "iles aland" },
            { "name": "iles caimanes" },
            { "name": "iles cocos (keeling)" },
            { "name": "iles cook" },
            { "name": "iles feroe" },
            { "name": "iles malouines" },
            { "name": "iles mariannes du nord" },
            { "name": "iles marshall" },
            { "name": "iles pitcairn" },
            { "name": "iles salomon" },
            { "name": "iles turks et caiques" },
            { "name": "iles vierges britanniques" },
            { "name": "iles vierges des etats-unis" },
            { "name": "inde" },
            { "name": "indonesie" },
            { "name": "iran" },
            { "name": "iraq" },
            { "name": "irlande" },
            { "name": "islande" },
            { "name": "israel" },
            { "name": "italie" },
            { "name": "jamaique" },
            { "name": "japon" },
            { "name": "jordanie" },
            { "name": "kazakhstan" },
            { "name": "kenya" },
            { "name": "kirghizistan" },
            { "name": "kiribati" },
            { "name": "koweit" },
            { "name": "laos" },
            { "name": "le vatican" },
            { "name": "lesotho" },
            { "name": "lettonie" },
            { "name": "liban" },
            { "name": "liberia" },
            { "name": "libye" },
            { "name": "liechtenstein" },
            { "name": "lituanie" },
            { "name": "luxembourg" },
            { "name": "macao" },
            { "name": "madagascar" },
            { "name": "malaisie" },
            { "name": "malawi" },
            { "name": "maldives" },
            { "name": "mali" },
            { "name": "malte" },
            { "name": "maroc" },
            { "name": "martinique" },
            { "name": "maurice" },
            { "name": "mauritanie" },
            { "name": "mayotte" },
            { "name": "mexique" },
            { "name": "moldavie" },
            { "name": "monaco" },
            { "name": "mongolie" },
            { "name": "montenegro" },
            { "name": "montserrat" },
            { "name": "mozambique" },
            { "name": "namibie" },
            { "name": "nauru" },
            { "name": "nepal" },
            { "name": "nicaragua" },
            { "name": "niger" },
            { "name": "nigeria" },
            { "name": "niue" },
            { "name": "norvege" },
            { "name": "nouvelle-caledonie" },
            { "name": "nouvelle-zelande" },
            { "name": "oman" },
            { "name": "ouganda" },
            { "name": "ouzbekistan" },
            { "name": "pakistan" },
            { "name": "palaos" },
            { "name": "panama" },
            { "name": "papouasie-nouvelle-guinee" },
            { "name": "paraguay" },
            { "name": "pays-bas" },
            { "name": "perou" },
            { "name": "philippines" },
            { "name": "pologne" },
            { "name": "polynesie francaise" },
            { "name": "porto rico" },
            { "name": "portugal" },
            { "name": "qatar" },
            { "name": "republique centrafricaine" },
            { "name": "republique de macedoine" },
            { "name": "republique democratique du congo" },
            { "name": "republique dominicaine" },
            { "name": "republique du congo" },
            { "name": "republique tcheque" },
            { "name": "reunion" },
            { "name": "roumanie" },
            { "name": "royaume-uni" },
            { "name": "russie" },
            { "name": "rwanda" },
            { "name": "sahara occidental" },
            { "name": "saint-kitts-et-nevis" },
            { "name": "saint-marin" },
            { "name": "saint-pierre-et-miquelon" },
            { "name": "saint-vincent-et-les grenadines" },
            { "name": "sainte-helene" },
            { "name": "sainte-lucie" },
            { "name": "salvador" },
            { "name": "samoa" },
            { "name": "samoa americaines" },
            { "name": "sao tome-et-principe" },
            { "name": "senegal" },
            { "name": "serbie" },
            { "name": "seychelles" },
            { "name": "sierra leone" },
            { "name": "singapour" },
            { "name": "slovaquie" },
            { "name": "slovenie" },
            { "name": "somalie" },
            { "name": "soudan" },
            { "name": "sri lanka" },
            { "name": "suede" },
            { "name": "suisse" },
            { "name": "suriname" },
            { "name": "svalbard et jan mayen" },
            { "name": "swaziland" },
            { "name": "syrie" },
            { "name": "tadjikistan" },
            { "name": "taiwan" },
            { "name": "tanzanie" },
            { "name": "tchad" },
            { "name": "terres australes francaises" },
            { "name": "thailande" },
            { "name": "timor oriental" },
            { "name": "togo" },
            { "name": "tonga" },
            { "name": "trinite-et-tobago" },
            { "name": "tunisie" },
            { "name": "turkmenistan" },
            { "name": "turquie" },
            { "name": "tuvalu" },
            { "name": "ukraine" },
            { "name": "uruguay" },
            { "name": "xinjiang" },
            { "name": "vanuatu" },
            { "name": "venezuela" },
            { "name": "viet nam" },
            { "name": "wallis et futuna" },
            { "name": "yemen" },
            { "name": "zambie" },
            { "name": "zimbabwe" }],

        "voiture": [
            { "name": "abarth" },
            { "name": "ac" },
            { "name": "acrea" },
            { "name": "yue Loong" },
            { "name": "acura" },
            { "name": "ad tramontana" },
            { "name": "adler" },
            { "name": "aixam" },
            { "name": "al melling" },
            { "name": "aleko" },
            { "name": "alfa romeo" },
            { "name": "alpina" },
            { "name": "alpine" },
            { "name": "alvis" },
            { "name": "amc" },
            { "name": "amphicar" },
            { "name": "aptera motors" },
            { "name": "ariel" },
            { "name": "armstrong siddeley" },
            { "name": "aro" },
            { "name": "artega" },
            { "name": "ascari" },
            { "name": "aston martin" },
            { "name": "audi" },
            { "name": "austin" },
            { "name": "austin healey" },
            { "name": "auto union" },
            { "name": "autobianchi" },
            { "name": "auverland" },
            { "name": "bee automobiles" },
            { "name": "bellier" },
            { "name": "bentley" },
            { "name": "berliet" },
            { "name": "bertone" },
            { "name": "bitter" },
            { "name": "bizzarrini" },
            { "name": "bmw" },
            { "name": "bollore" },
            { "name": "bongarini" },
            { "name": "booxt" },
            { "name": "borgward" },
            { "name": "bowler" },
            { "name": "brabus" },
            { "name": "bremach" },
            { "name": "brilliance" },
            { "name": "bristol" },
            { "name": "brooke cars" },
            { "name": "bugatti" },
            { "name": "buick" },
            { "name": "burby s" },
            { "name": "byd" },
            { "name": "cadillac" },
            { "name": "caparo" },
            { "name": "carbodies" },
            { "name": "carbontech" },
            { "name": "carver" },
            { "name": "casalini" },
            { "name": "caterham" },
            { "name": "cg" },
            { "name": "chatenet" },
            { "name": "chenard et walcker" },
            { "name": "chery" },
            { "name": "chevrolet" },
            { "name": "china automobile" },
            { "name": "chrysler" },
            { "name": "citroen" },
            { "name": "clenet" },
            { "name": "commuter cars" },
            { "name": "connaught" },
            { "name": "coste" },
            { "name": "courb" },
            { "name": "cupra" },
            { "name": "dacia" },
            { "name": "daewoo" },
            { "name": "daf" },
            { "name": "daihatsu" },
            { "name": "daimler" },
            { "name": "dallara" },
            { "name": "dangel" },
            { "name": "darmont" },
            { "name": "datsun" },
            { "name": "de fremond" },
            { "name": "de la chapelle" },
            { "name": "de lorean" },
            { "name": "de soto" },
            { "name": "de tomaso" },
            { "name": "delage" },
            { "name": "delahaye" },
            { "name": "deronda" },
            { "name": "deutsch-bonnet" },
            { "name": "devon" },
            { "name": "dkw" },
            { "name": "dodge" },
            { "name": "dongfeng" },
            { "name": "donkervoort" },
            { "name": "donnet" },
            { "name": "dr motor" },
            { "name": "ds" },
            { "name": "due" },
            { "name": "duesenberg" },
            { "name": "eagle" },
            { "name": "ebro" },
            { "name": "edsel" },
            { "name": "elv" },
            { "name": "erad" },
            { "name": "estrima" },
            { "name": "exagon motors" },
            { "name": "excalibur" },
            { "name": "facel vega" },
            { "name": "fam automobiles" },
            { "name": "faralli & mazzanti" },
            { "name": "farbio" },
            { "name": "ferrari" },
            { "name": "fiat" },
            { "name": "fioravanti" },
            { "name": "fisker" },
            { "name": "ford" },
            { "name": "fornasari" },
            { "name": "fso" },
            { "name": "gac gonow" },
            { "name": "geely" },
            { "name": "genesis" },
            { "name": "gillet" },
            { "name": "ginetta" },
            { "name": "glas" },
            { "name": "gmc" },
            { "name": "gme" },
            { "name": "grandin" },
            { "name": "great wall" },
            { "name": "grecav" },
            { "name": "gumpert" },
            { "name": "healey" },
            { "name": "helem" },
            { "name": "heuliez" },
            { "name": "hillman" },
            { "name": "holden" },
            { "name": "hommell" },
            { "name": "honda" },
            { "name": "hotchkiss" },
            { "name": "howmet" },
            { "name": "hudson" },
            { "name": "humber" },
            { "name": "hummer" },
            { "name": "hyundai" },
            { "name": "imperial" },
            { "name": "infiniti" },
            { "name": "innocenti" },
            { "name": "innotech" },
            { "name": "intermeccanica" },
            { "name": "international" },
            { "name": "invicta" },
            { "name": "iso" },
            { "name": "isorivolta" },
            { "name": "isuzu" },
            { "name": "italcar" },
            { "name": "iveco" },
            { "name": "jaguar" },
            { "name": "jdm simpa" },
            { "name": "jeep" },
            { "name": "jensen" },
            { "name": "kassbohrer setra" },
            { "name": "kia" },
            { "name": "koenigsegg" },
            { "name": "ktm" },
            { "name": "lada" },
            { "name": "lagonda" },
            { "name": "lamborghini" },
            { "name": "lancia" },
            { "name": "land rover" },
            { "name": "landwind" },
            { "name": "lantana" },
            { "name": "laraki" },
            { "name": "ldv" },
            { "name": "lexus" },
            { "name": "ligier" },
            { "name": "lincoln" },
            { "name": "lister" },
            { "name": "little" },
            { "name": "lola" },
            { "name": "london taxi company" },
            { "name": "loremo" },
            { "name": "lotus" },
            { "name": "lumeneo" },
            { "name": "lynk & co" },
            { "name": "mahindra" },
            { "name": "man" },
            { "name": "marcadier" },
            { "name": "marcos" },
            { "name": "martin" },
            { "name": "marussia" },
            { "name": "maruti" },
            { "name": "maserati" },
            { "name": "matra" },
            { "name": "maybach" },
            { "name": "mazda" },
            { "name": "mclaren" },
            { "name": "mdi" },
            { "name": "mega" },
            { "name": "melkus" },
            { "name": "mercedes" },
            { "name": "mercedes-amg" },
            { "name": "mercury" },
            { "name": "mev" },
            { "name": "meyers manx" },
            { "name": "mg" },
            { "name": "mia electric" },
            { "name": "microcar" },
            { "name": "minauto" },
            { "name": "mini" },
            { "name": "mitsubishi" },
            { "name": "mitsubishi fuso" },
            { "name": "mitsuoka" },
            { "name": "monteverdi" },
            { "name": "morgan" },
            { "name": "morris" },
            { "name": "mosler" },
            { "name": "mpm motors" },
            { "name": "mvs" },
            { "name": "mygale" },
            { "name": "nanjing" },
            { "name": "nash" },
            { "name": "neckar" },
            { "name": "newteon" },
            { "name": "nissan" },
            { "name": "noble" },
            { "name": "noun electric" },
            { "name": "nsu" },
            { "name": "numexia" },
            { "name": "oldsmobile" },
            { "name": "opel" },
            { "name": "osi" },
            { "name": "packard" },
            { "name": "pagani" },
            { "name": "panhard" },
            { "name": "panoz" },
            { "name": "panther" },
            { "name": "pegaso" },
            { "name": "perana" },
            { "name": "peugeot" },
            { "name": "pgo" },
            { "name": "piaggio" },
            { "name": "pilbeam" },
            { "name": "plymouth" },
            { "name": "polestar" },
            { "name": "polski" },
            { "name": "pontiac" },
            { "name": "porsche" },
            { "name": "proton" },
            { "name": "protoscar" },
            { "name": "qoros" },
            { "name": "quant" },
            { "name": "radical" },
            { "name": "reliant" },
            { "name": "renault" },
            { "name": "renault trucks" },
            { "name": "rene bonnet" },
            { "name": "reva" },
            { "name": "reynard" },
            { "name": "riley" },
            { "name": "rinspeed" },
            { "name": "rolls royce" },
            { "name": "ronart" },
            { "name": "rosengart" },
            { "name": "rover" },
            { "name": "russo-baltique" },
            { "name": "saab" },
            { "name": "saleen" },
            { "name": "salica" },
            { "name": "salmson" },
            { "name": "samsung" },
            { "name": "santana" },
            { "name": "saturn" },
            { "name": "savel" },
            { "name": "saviem" },
            { "name": "sbarro" },
            { "name": "scania" },
            { "name": "scion" },
            { "name": "seat" },
            { "name": "secma" },
            { "name": "shelby" },
            { "name": "shuanghuan" },
            { "name": "simca" },
            { "name": "singer" },
            { "name": "sivax" },
            { "name": "skoda" },
            { "name": "smart" },
            { "name": "sms" },
            { "name": "sovamag" },
            { "name": "spectre" },
            { "name": "spyker" },
            { "name": "srt" },
            { "name": "ssangyong" },
            { "name": "ssc" },
            { "name": "studebaker" },
            { "name": "stutz" },
            { "name": "subaru" },
            { "name": "sunbeam" },
            { "name": "suzuki" },
            { "name": "talbot simca" },
            { "name": "tata" },
            { "name": "teilhol" },
            { "name": "tesla" },
            { "name": "think" },
            { "name": "toyota" },
            { "name": "trabant" },
            { "name": "triumph" },
            { "name": "tvr" },
            { "name": "ultima" },
            { "name": "umm" },
            { "name": "vaillante" },
            { "name": "van hool" },
            { "name": "vanden plas" },
            { "name": "vauxhall" },
            { "name": "venturi" },
            { "name": "veritas" },
            { "name": "vespa" },
            { "name": "virago" },
            { "name": "volkswagen" },
            { "name": "volteis" },
            { "name": "volvo" },
            { "name": "volvo trucks" },
            { "name": "westfield" },
            { "name": "wiesmann" },
            { "name": "willys" },
            { "name": "wolseley" },
            { "name": "xinyang" },
            { "name": "zagato" },
            { "name": "zap" },
            { "name": "zastava" },
            { "name": "zenn" },
            { "name": "zenvo" }],

        "couleur": [{ "name": "abricot" },
        { "name": "acajou" },
        { "name": "aigue-marine" },
        { "name": "alezan " },
        { "name": "amande" },
        { "name": "amarante" },
        { "name": "ambre" },
        { "name": "amethyste" },
        { "name": "dorian" },
        { "name": "queue-de-vache" },
        { "name": "ucla" },
        { "name": "wenge" },
        { "name": "xanadu" },
        { "name": "yale" },
        { "name": "anthracite" },
        { "name": "aquilain" },
        { "name": "ardoise" },
        { "name": "aubergine" },
        { "name": "auburn" },
        { "name": "aurore" },
        { "name": "avocat" },
        { "name": "azur" },
        { "name": "baillet" },
        { "name": "basane" },
        { "name": "beige" },
        { "name": "beurre" },
        { "name": "bis" },
        { "name": "bisque" },
        { "name": "bistre" },
        { "name": "bitume" },
        { "name": "blanc" },
        { "name": "blanc casse" },
        { "name": "blanc lunaire" },
        { "name": "ble" },
        { "name": "bleu" },
        { "name": "bleu acier" },
        { "name": "bleu barbeau" },
        { "name": "bleu canard" },
        { "name": "bleu celeste" },
        { "name": "bleu charrette" },
        { "name": "bleu ciel" },
        { "name": "bleu de cobalt" },
        { "name": "bleu de prusse" },
        { "name": "bleu electrique" },
        { "name": "bleu givre" },
        { "name": "bleu klein" },
        { "name": "bleu majorelle" },
        { "name": "bleu marine" },
        { "name": "bleu nuit" },
        { "name": "bleu outremer" },
        { "name": "bleu paon" },
        { "name": "bleu persan" },
        { "name": "bleu petrole" },
        { "name": "bleu roi " },
        { "name": "bleu turquin" },
        { "name": "blond " },
        { "name": "blond venitien" },
        { "name": "bordeaux" },
        { "name": "bouton d'or" },
        { "name": "brique" },
        { "name": "bronze" },
        { "name": "brou de noix" },
        { "name": "brun" },
        { "name": "caca d'oie" },
        { "name": "cacao" },
        { "name": "cachou" },
        { "name": "cæruleum" },
        { "name": "cafe" },
        { "name": "cafe au lait" },
        { "name": "cannelle" },
        { "name": "capucine" },
        { "name": "caramel " },
        { "name": "carmin " },
        { "name": "carotte" },
        { "name": "chamois" },
        { "name": "chartreuse" },
        { "name": "chatain" },
        { "name": "chaudron" },
        { "name": "chocolat" },
        { "name": "cinabre" },
        { "name": "citrouille" },
        { "name": "coquille d'œuf" },
        { "name": "corail" },
        { "name": "cramoisi" },
        { "name": "creme" },
        { "name": "cuisse de nymphe" },
        { "name": "cuivre" },
        { "name": "cyan" },
        { "name": "ecarlate" },
        { "name": "ecru" },
        { "name": "emeraude" },
        { "name": "fauve" },
        { "name": "flave" },
        { "name": "fraise" },
        { "name": "fraise ecrasee" },
        { "name": "framboise" },
        { "name": "fuchsia" },
        { "name": "fumee" },
        { "name": "garance" },
        { "name": "glauque" },
        { "name": "glycine" },
        { "name": "grege" },
        { "name": "grenadine" },
        { "name": "grenat" },
        { "name": "gris" },
        { "name": "gris acier" },
        { "name": "gris de payne" },
        { "name": "gris fer" },
        { "name": "gris perle" },
        { "name": "groseille" },
        { "name": "gueules" },
        { "name": "heliotrope" },
        { "name": "incarnat" },
        { "name": "indigo" },
        { "name": "indigo" },
        { "name": "isabelle" },
        { "name": "ivoire" },
        { "name": "jaune" },
        { "name": "jaune canari" },
        { "name": "jaune citron" },
        { "name": "jaune d'or" },
        { "name": "jaune de cobalt" },
        { "name": "jaune de mars" },
        { "name": "jaune de naples" },
        { "name": "jaune imperial" },
        { "name": "jaune mimosa" },
        { "name": "kaki" },
        { "name": "lapis-lazuli" },
        { "name": "lavalliere" },
        { "name": "lavande" },
        { "name": "lie de vin" },
        { "name": "lilas" },
        { "name": "lime" },
        { "name": "lin" },
        { "name": "magenta" },
        { "name": "mais" },
        { "name": "malachite" },
        { "name": "mandarine" },
        { "name": "marron" },
        { "name": "mastic" },
        { "name": "mauve" },
        { "name": "menthe" },
        { "name": "moutarde" },
        { "name": "nacarat" },
        { "name": "nankin" },
        { "name": "noir" },
        { "name": "noisette" },
        { "name": "ocre jaune" },
        { "name": "ocre rouge" },
        { "name": "olive" },
        { "name": "or" },
        { "name": "orange" },
        { "name": "orange brule" },
        { "name": "orchidee" },
        { "name": "orpiment" },
        { "name": "paille" },
        { "name": "parme" },
        { "name": "pelure d'oignon" },
        { "name": "pervenche" },
        { "name": "pistache" },
        { "name": "poil de chameau" },
        { "name": "ponceau" },
        { "name": "pourpre" },
        { "name": "prasin" },
        { "name": "prune" },
        { "name": "puce" },
        { "name": "rose" },
        { "name": "rose mountbatten" },
        { "name": "rouge" },
        { "name": "rouge anglais" },
        { "name": "rouge cardinal" },
        { "name": "rouge cerise" },
        { "name": "rouge d'andrinople" },
        { "name": "rouge de falun" },
        { "name": "rouge feu" },
        { "name": "rouge feu" },
        { "name": "rouge sang" },
        { "name": "rouge tomette" },
        { "name": "rouille" },
        { "name": "roux" },
        { "name": "rubis" },
        { "name": "sable" },
        { "name": "safre" },
        { "name": "sang de bœuf" },
        { "name": "sanguine" },
        { "name": "saphir" },
        { "name": "saumon" },
        { "name": "sepia" },
        { "name": "sinople" },
        { "name": "smalt" },
        { "name": "smaragdin" },
        { "name": "soufre" },
        { "name": "souris" },
        { "name": "tabac" },
        { "name": "taupe" },
        { "name": "terre d'ombre" },
        { "name": "tomate" },
        { "name": "topaze" },
        { "name": "tourterelle" },
        { "name": "turquoise" },
        { "name": "vanille" },
        { "name": "vermeil" },
        { "name": "vermillon" },
        { "name": "vert" },
        { "name": "vert bouteille" },
        { "name": "vert celadon" },
        { "name": "vert d'eau" },
        { "name": "vert de chrome" },
        { "name": "vert de hooker" },
        { "name": "vert de vessie" },
        { "name": "vert epinard" },
        { "name": "vert imperial" },
        { "name": "vert lichen" },
        { "name": "vert perroquet" },
        { "name": "vert poireau" },
        { "name": "vert pomme" },
        { "name": "vert prairie" },
        { "name": "vert printemps" },
        { "name": "vert sapin" },
        { "name": "vert sauge" },
        { "name": "vert tilleul" },
        { "name": "vert veronese" },
        { "name": "vert-de-gris" },
        { "name": "violet" },
        { "name": "violet d'eveque" },
        { "name": "viride" },
        { "name": "zinzolin" }],

        "mammiferes": [{ "name": "acouchi" },
        { "name": "addax" },
        { "name": "agouti" },
        { "name": "ai" },
        { "name": "alactaga" },
        { "name": "algazelle" },
        { "name": "allocebe" },
        { "name": "almiqui" },
        { "name": "alouate" },
        { "name": "alpaga" },
        { "name": "ane" },
        { "name": "angwantibo" },
        { "name": "anoa" },
        { "name": "anomalure" },
        { "name": "antilope" },
        { "name": "atele" },
        { "name": "aulacode" },
        { "name": "avahi" },
        { "name": "aye-aye" },
        { "name": "babiroussa" },
        { "name": "babouin" },
        { "name": "baiji" },
        { "name": "baleine" },
        { "name": "baleine a bec" },
        { "name": "balenoptere" },
        { "name": "balisaur" },
        { "name": "bandar" },
        { "name": "bandicoot" },
        { "name": "banteng" },
        { "name": "barasinga ou barasingha" },
        { "name": "barbastelle" },
        { "name": "baribal" },
        { "name": "beira" },
        { "name": "belette" },
        { "name": "beluga" },
        { "name": "berardie" },
        { "name": "bharal" },
        { "name": "biche-cochon" },
        { "name": "binturong" },
        { "name": "bison" },
        { "name": "blaireau" },
        { "name": "bleebok" },
        { "name": "bœuf musque" },
        { "name": "bœuf" },
        { "name": "bongo" },
        { "name": "bonobo" },
        { "name": "bonto" },
        { "name": "bororo" },
        { "name": "bouquetin" },
        { "name": "bruan" },
        { "name": "bubale" },
        { "name": "buffle" },
        { "name": "cabassou" },
        { "name": "caberu" },
        { "name": "cabiai" },
        { "name": "cachalot" },
        { "name": "callicebe" },
        { "name": "callitriche" },
        { "name": "campagnol" },
        { "name": "capucin" },
        { "name": "capybara" },
        { "name": "caracal" },
        { "name": "carcajou" },
        { "name": "caribou" },
        { "name": "castor" },
        { "name": "castor de montagne" },
        { "name": "cephalophe" },
        { "name": "cercocebe" },
        { "name": "cercopitheque" },
        { "name": "cerf" },
        { "name": "chacal" },
        { "name": "chameau" },
        { "name": "chamois" },
        { "name": "chat" },
        { "name": "chaus" },
        { "name": "chauve-souris" },
        { "name": "cheval" },
        { "name": "chevalin" },
        { "name": "chevre" },
        { "name": "chevreuil" },
        { "name": "chevrotain porte-musc" },
        { "name": "chien de prairie" },
        { "name": "chien" },
        { "name": "chimpanze" },
        { "name": "chinchilla" },
        { "name": "chinkara" },
        { "name": "chirogale" },
        { "name": "choeropotame" },
        { "name": "chousingha" },
        { "name": "chozchoz" },
        { "name": "chungungo" },
        { "name": "civette" },
        { "name": "coati" },
        { "name": "cobaye" },
        { "name": "cobe" },
        { "name": "cochon d'inde" },
        { "name": "cochon" },
        { "name": "colobe" },
        { "name": "colocolo" },
        { "name": "colugo" },
        { "name": "condylure" },
        { "name": "coruro" },
        { "name": "couguar" },
        { "name": "couscous" },
        { "name": "coyote" },
        { "name": "crocidure" },
        { "name": "cynhyene" },
        { "name": "cynocephale" },
        { "name": "daguet" },
        { "name": "daman" },
        { "name": "daim" },
        { "name": "damalisque" },
        { "name": "dasyure" },
        { "name": "dauphin" },
        { "name": "degue" },
        { "name": "degue du chili" },
        { "name": "dendrolague" },
        { "name": "desman" },
        { "name": "dhole" },
        { "name": "diable de tasmanie" },
        { "name": "dibatag" },
        { "name": "dik-dik" },
        { "name": "dingo" },
        { "name": "douc" },
        { "name": "douroucouli" },
        { "name": "drill" },
        { "name": "dromadaire" },
        { "name": "dugong" },
        { "name": "duiker" },
        { "name": "ecureuil antilope" },
        { "name": "ecureuil fouisseur" },
        { "name": "ecureuil volant" },
        { "name": "ecureuil" },
        { "name": "elan" },
        { "name": "eland" },
        { "name": "elaphode" },
        { "name": "elephant" },
        { "name": "elephant de mer" },
        { "name": "entelle" },
        { "name": "epaulard" },
        { "name": "epomophore" },
        { "name": "euplere" },
        { "name": "eyra" },
        { "name": "falanouc" },
        { "name": "faon" },
        { "name": "fennec" },
        { "name": "feuillard" },
        { "name": "fossa" },
        { "name": "fouine" },
        { "name": "fourmilier" },
        { "name": "fourmilier marsupial" },
        { "name": "foussa" },
        { "name": "furet" },
        { "name": "galago" },
        { "name": "galeopitheque" },
        { "name": "gaufre ou gauphre" },
        { "name": "gaur" },
        { "name": "gayal" },
        { "name": "gazelle" },
        { "name": "gelada" },
        { "name": "gemsbok" },
        { "name": "genette" },
        { "name": "gerbille" },
        { "name": "gerboise" },
        { "name": "gerenuk" },
        { "name": "gibbon" },
        { "name": "girafe" },
        { "name": "globicephale" },
        { "name": "glouton" },
        { "name": "gnou" },
        { "name": "goral" },
        { "name": "gorille" },
        { "name": "goundi" },
        { "name": "grison" },
        { "name": "grizzly" },
        { "name": "grysbok" },
        { "name": "guanaco" },
        { "name": "guemal" },
        { "name": "guenon " },
        { "name": "guepard" },
        { "name": "guereza" },
        { "name": "guib" },
        { "name": "hamster" },
        { "name": "herisson" },
        { "name": "hermine" },
        { "name": "hippopotame" },
        { "name": "hippotrague" },
        { "name": "hirola" },
        { "name": "hocheur" },
        { "name": "homme" },
        { "name": "houlock" },
        { "name": "huillin" },
        { "name": "hurleur" },
        { "name": "hutia" },
        { "name": "hyene" },
        { "name": "hylochere" },
        { "name": "hypotrague" },
        { "name": "ibex" },
        { "name": "impala" },
        { "name": "indri" },
        { "name": "isard" },
        { "name": "isatis" },
        { "name": "jaguar" },
        { "name": "jaguarondi" },
        { "name": "jharal" },
        { "name": "jubarte" },
        { "name": "jutia" },
        { "name": "kanchil" },
        { "name": "kangourou" },
        { "name": "kinkajou" },
        { "name": "koala" },
        { "name": "kob" },
        { "name": "kodiak" },
        { "name": "kodkod" },
        { "name": "koudou" },
        { "name": "kouprey" },
        { "name": "lagotriche" },
        { "name": "lama" },
        { "name": "lamantin" },
        { "name": "lapin" },
        { "name": "lar" },
        { "name": "lemming" },
        { "name": "lemur" },
        { "name": "leopard des mers" },
        { "name": "leopard" },
        { "name": "lepilemur" },
        { "name": "lerot" },
        { "name": "lerotin" },
        { "name": "lievre" },
        { "name": "lievre sauteur" },
        { "name": "lievre-wallaby" },
        { "name": "linsang" },
        { "name": "lion" },
        { "name": "lion de mer" },
        { "name": "loir" },
        { "name": "loris" },
        { "name": "loup" },
        { "name": "loup-marsupial" },
        { "name": "loutre" },
        { "name": "luwak" },
        { "name": "lycaon" },
        { "name": "lynx" },
        { "name": "macaque" },
        { "name": "macrorhine" },
        { "name": "macroscelide" },
        { "name": "magistrat" },
        { "name": "magot" },
        { "name": "maipouri" },
        { "name": "maki" },
        { "name": "mammouth" },
        { "name": "mandrill" },
        { "name": "mangabey" },
        { "name": "mangouste" },
        { "name": "mangue ou mangue" },
        { "name": "mara" },
        { "name": "margay" },
        { "name": "markhor" },
        { "name": "marmotte" },
        { "name": "marmouset" },
        { "name": "marsouin" },
        { "name": "marte" },
        { "name": "martre" },
        { "name": "mazame" },
        { "name": "megaloglosse" },
        { "name": "microcebe" },
        { "name": "minioptere" },
        { "name": "molosse" },
        { "name": "monito del monte" },
        { "name": "morse" },
        { "name": "mouffette" },
        { "name": "mouflon" },
        { "name": "mouton" },
        { "name": "moustac" },
        { "name": "mulot" },
        { "name": "muntjac" },
        { "name": "murin" },
        { "name": "musang" },
        { "name": "musaraigne" },
        { "name": "myrmecobie" },
        { "name": "myrmidon" },
        { "name": "narval" },
        { "name": "nasique" },
        { "name": "natalide" },
        { "name": "ninguai" },
        { "name": "noctilion" },
        { "name": "nunbat" },
        { "name": "nyala" },
        { "name": "nyctere" },
        { "name": "nycticebe" },
        { "name": "ocelot" },
        { "name": "octodon" },
        { "name": "okapi" },
        { "name": "olingo" },
        { "name": "once" },
        { "name": "ondatra" },
        { "name": "opossum" },
        { "name": "orang-outan" },
        { "name": "oreillard" },
        { "name": "oreotrague" },
        { "name": "orignal" },
        { "name": "orque" },
        { "name": "orycterope" },
        { "name": "oryx" },
        { "name": "otarie" },
        { "name": "otocyon" },
        { "name": "ouakari" },
        { "name": "ouanderou" },
        { "name": "ouistiti" },
        { "name": "ourebi" },
        { "name": "ours" },
        { "name": "ornithorynque" },
        { "name": "paca" },
        { "name": "pacarana" },
        { "name": "pademelon" },
        { "name": "pain a cacheter" },
        { "name": "panda" },
        { "name": "pangolin" },
        { "name": "panthere" },
        { "name": "paresseux" },
        { "name": "patas" },
        { "name": "pecari" },
        { "name": "pekan" },
        { "name": "petauriste" },
        { "name": "petrodrome" },
        { "name": "petrogale" },
        { "name": "phacochere" },
        { "name": "phalanger" },
        { "name": "phaner" },
        { "name": "phoque" },
        { "name": "phyllorine" },
        { "name": "pika" },
        { "name": "pinche" },
        { "name": "pipistrelle" },
        { "name": "poiane" },
        { "name": "polatouche" },
        { "name": "porc" },
        { "name": "porc-epic" },
        { "name": "possum" },
        { "name": "potamochere" },
        { "name": "potamogale" },
        { "name": "potto" },
        { "name": "poudou" },
        { "name": "pronghorn" },
        { "name": "protele" },
        { "name": "pteronote" },
        { "name": "puku" },
        { "name": "puma" },
        { "name": "putois" },
        { "name": "quagga" },
        { "name": "quatre yeux" },
        { "name": "quokka" },
        { "name": "ragondin" },
        { "name": "rasse" },
        { "name": "rat des pharaons" },
        { "name": "rat musque" },
        { "name": "rat taupe" },
        { "name": "rat" },
        { "name": "rat a criniere" },
        { "name": "rat a trompe" },
        { "name": "ratel" },
        { "name": "rat-kangourou" },
        { "name": "raton laveur" },
        { "name": "renard" },
        { "name": "renard polaire" },
        { "name": "renne" },
        { "name": "rhesus" },
        { "name": "rhinoceros" },
        { "name": "rhinopitheque" },
        { "name": "rhinopome" },
        { "name": "rhynchocyon" },
        { "name": "rorqual" },
        { "name": "roussette" },
        { "name": "sagouin" },
        { "name": "saimiri" },
        { "name": "sajou" },
        { "name": "saki" },
        { "name": "sambar" },
        { "name": "sanglier" },
        { "name": "sapajou" },
        { "name": "sarigue" },
        { "name": "sassa" },
        { "name": "semnopitheque" },
        { "name": "serotine" },
        { "name": "serow" },
        { "name": "serval" },
        { "name": "siamang" },
        { "name": "siciste" },
        { "name": "sifaka" },
        { "name": "singe" },
        { "name": "singe-araignee" },
        { "name": "singe-ecureuil" },
        { "name": "singe de nuit" },
        { "name": "singe laineux" },
        { "name": "singe vert" },
        { "name": "sitatunga" },
        { "name": "solenodon" },
        { "name": "sotalie" },
        { "name": "souris" },
        { "name": "souris a miel" },
        { "name": "souris marsupiale" },
        { "name": "sousouc" },
        { "name": "souslik" },
        { "name": "spermophile" },
        { "name": "springbok" },
        { "name": "steenbok" },
        { "name": "steno" },
        { "name": "suisse" },
        { "name": "suricate" },
        { "name": "tadaride" },
        { "name": "tahr" },
        { "name": "takin" },
        { "name": "talapoin" },
        { "name": "tamanoir" },
        { "name": "tamarau" },
        { "name": "tamarin" },
        { "name": "tamarin-lion" },
        { "name": "tamia" },
        { "name": "tangue" },
        { "name": "taphien" },
        { "name": "tarsier" },
        { "name": "tatou" },
        { "name": "taupe" },
        { "name": "taupe doree" },
        { "name": "taupe marsupiale" },
        { "name": "taureau" },
        { "name": "tayra" },
        { "name": "telagon" },
        { "name": "tenrec" },
        { "name": "thylacine" },
        { "name": "tigre de tasmanie" },
        { "name": "tigre" },
        { "name": "titi" },
        { "name": "topi" },
        { "name": "toupaye" },
        { "name": "trident" },
        { "name": "triok" },
        { "name": "tuco-tuco" },
        { "name": "unau" },
        { "name": "urial" },
        { "name": "vache" },
        { "name": "vampire" },
        { "name": "vaquita" },
        { "name": "veau marin" },
        { "name": "veau" },
        { "name": "vervet" },
        { "name": "vespertilion" },
        { "name": "vigogne" },
        { "name": "viscache" },
        { "name": "vison" },
        { "name": "wallaby" },
        { "name": "wapiti" },
        { "name": "wolverine" },
        { "name": "wombat" },
        { "name": "xerus" },
        { "name": "yak" },
        { "name": "yangir" },
        { "name": "zapode" },
        { "name": "zebre" },
        { "name": "zebu" },
        { "name": "zibeline" },
        { "name": "zibeth" },
        { "name": "zokor" },
        { "name": "zorille" },
        { "name": "zyzomys" }],

        "instrument": [{ "name": "aboes" },
        { "name": "accordeon" },
        { "name": "accordeon diatonique" },
        { "name": "accordina" },
        { "name": "adjalin" },
        { "name": "aerophon" },
        { "name": "agogo" },
        { "name": "alboka" },
        { "name": "alghoza" },
        { "name": "allun" },
        { "name": "alto" },
        { "name": "angklung" },
        { "name": "antsiva" },
        { "name": "appeau" },
        { "name": "archiluth" },
        { "name": "arghoul " },
        { "name": "atabaque" },
        { "name": "autoharpe" },
        { "name": "baglama " },
        { "name": "balafon" },
        { "name": "balalaika" },
        { "name": "bandola" },
        { "name": "bandoneon" },
        { "name": "bandoura " },
        { "name": "bangdi" },
        { "name": "banjo" },
        { "name": "banshri" },
        { "name": "barbitos" },
        { "name": "baryton" },
        { "name": "basson" },
        { "name": "bata" },
        { "name": "baton de pluie" },
        { "name": "batterie" },
        { "name": "batterie electronique" },
        { "name": "bayan " },
        { "name": "bechonnet " },
        { "name": "belek " },
        { "name": "bendir " },
        { "name": "benju" },
        { "name": "berimbau" },
        { "name": "biniou" },
        { "name": "birbyne" },
        { "name": "biwa" },
        { "name": "bobre" },
        { "name": "bodega " },
        { "name": "bodhran " },
        { "name": "boha" },
        { "name": "bomba" },
        { "name": "bombarde" },
        { "name": "bombardon" },
        { "name": "bombo" },
        { "name": "bongo " },
        { "name": "bourdon" },
        { "name": "bouzouki" },
        { "name": "bratsch " },
        { "name": "bugle" },
        { "name": "bulbultara" },
        { "name": "cabasa" },
        { "name": "cabrette" },
        { "name": "caisse claire" },
        { "name": "caixa" },
        { "name": "cajon" },
        { "name": "calebasse" },
        { "name": "caremere" },
        { "name": "carillon" },
        { "name": "carillon tubulaire" },
        { "name": "carnyx" },
        { "name": "castagnettes" },
        { "name": "caval" },
        { "name": "cavaquinho" },
        { "name": "caxixi" },
        { "name": "cecilium" },
        { "name": "celesta" },
        { "name": "cellulophone" },
        { "name": "chabrette" },
        { "name": "chalemie" },
        { "name": "chalumeau" },
        { "name": "chapeau chinois" },
        { "name": "chapey" },
        { "name": "charango" },
        { "name": "chitarra battente" },
        { "name": "chitarrone" },
        { "name": "choro" },
        { "name": "cialamella" },
        { "name": "cistre" },
        { "name": "cithare" },
        { "name": "clairon" },
        { "name": "clarinette" },
        { "name": "clarinette basse" },
        { "name": "clavecin" },
        { "name": "claves" },
        { "name": "clavicorde" },
        { "name": "clavicytherium" },
        { "name": "clavinet" },
        { "name": "clavi harp" },
        { "name": "cloche" },
        { "name": "cloches tubulaires" },
        { "name": "cobza" },
        { "name": "colachon" },
        { "name": "concertina" },
        { "name": "congas" },
        { "name": "conque" },
        { "name": "contrebasse" },
        { "name": "contrebasse a vent" },
        { "name": "contrebasson" },
        { "name": "cor anglais" },
        { "name": "cor d'harmonie" },
        { "name": "cor de basset" },
        { "name": "cor de chasse" },
        { "name": "cor des alpes" },
        { "name": "cor naturel" },
        { "name": "cornamuse" },
        { "name": "corne" },
        { "name": "corne de brume" },
        { "name": "cornemuse" },
        { "name": "cornet a bouquin" },
        { "name": "cornet a pistons" },
        { "name": "cornu" },
        { "name": "cosmophone" },
        { "name": "courtaud" },
        { "name": "cricket" },
        { "name": "cristal baschet" },
        { "name": "cromorne" },
        { "name": "crouth" },
        { "name": "cuatro" },
        { "name": "cuica" },
        { "name": "cuillers" },
        { "name": "cumbus" },
        { "name": "cura" },
        { "name": "cymbale" },
        { "name": "cymbales antiques" },
        { "name": "cymbalum" },
        { "name": "dabakan" },
        { "name": "daf" },
        { "name": "damana" },
        { "name": "danbolino" },
        { "name": "danhoun" },
        { "name": "danyen" },
        { "name": "dap" },
        { "name": "darbouka" },
        { "name": "darvyra" },
        { "name": "def" },
        { "name": "dehol" },
        { "name": "diapason" },
        { "name": "didgeridoo" },
        { "name": "dimplito" },
        { "name": "dizi" },
        { "name": "djembe" },
        { "name": "djoze" },
        { "name": "doedelzak" },
        { "name": "dolcian" },
        { "name": "domra" },
        { "name": "dongxiao" },
        { "name": "dou-co" },
        { "name": "doudoucaine" },
        { "name": "doudouk" },
        { "name": "dubreq stylophone" },
        { "name": "duda" },
        { "name": "dulcimer" },
        { "name": "dulcitone" },
        { "name": "dulzaina" },
        { "name": "dum dum" },
        { "name": "eigenharp" },
        { "name": "epinette" },
        { "name": "epinette des vosges" },
        { "name": "erhu" },
        { "name": "erkencho" },
        { "name": "euphone" },
        { "name": "euphonium" },
        { "name": "fifre" },
        { "name": "flabuta" },
        { "name": "flageolet" },
        { "name": "flaviol" },
        { "name": "flexatone" },
        { "name": "flute" },
        { "name": "flute a bec" },
        { "name": "flute basse" },
        { "name": "flute de pan" },
        { "name": "flute en sol" },
        { "name": "flute harmonique" },
        { "name": "flute irlandaise" },
        { "name": "flute traversiere" },
        { "name": "flute traversiere baroque" },
        { "name": "frestel" },
        { "name": "fujara" },
        { "name": "fut" },
        { "name": "gadoulka" },
        { "name": "gaida" },
        { "name": "gaita" },
        { "name": "gaita gallega" },
        { "name": "galoubet" },
        { "name": "gambri" },
        { "name": "gamelan" },
        { "name": "ganza" },
        { "name": "gardon" },
        { "name": "gasba" },
        { "name": "geige" },
        { "name": "gemshorn" },
        { "name": "gigue" },
        { "name": "gita" },
        { "name": "glassharmonica" },
        { "name": "glockenspiel" },
        { "name": "gong" },
        { "name": "graile" },
        { "name": "grelots" },
        { "name": "grosse caisse" },
        { "name": "guimbarde" },
        { "name": "guiro" },
        { "name": "guitare" },
        { "name": "guitare acoustique" },
        { "name": "guitare baroque" },
        { "name": "guitare baryton" },
        { "name": "guitare basse" },
        { "name": "guitare classique" },
        { "name": "guitare electrique" },
        { "name": "guitare electro-acoustique" },
        { "name": "guitare flamenca" },
        { "name": "guitare folk" },
        { "name": "guitare-harpe" },
        { "name": "guitare hawaienne" },
        { "name": "guitare portugaise" },
        { "name": "guitarron" },
        { "name": "guiterne" },
        { "name": "guqin" },
        { "name": "gusli" },
        { "name": "guzheng" },
        { "name": "guzla" },
        { "name": "hackbrett" },
        { "name": "hang" },
        { "name": "harmonica" },
        { "name": "harmonica de verre" },
        { "name": "harmoniflute" },
        { "name": "harmonium" },
        { "name": "harpe" },
        { "name": "harpe a pedales" },
        { "name": "harpe celtique" },
        { "name": "harpe chinoise" },
        { "name": "harpe d'afrique" },
        { "name": "harpe des pahouins" },
        { "name": "harpu" },
        { "name": "hautbois" },
        { "name": "hautbois baryton" },
        { "name": "hautbois d'amour" },
        { "name": "heckelphone" },
        { "name": "hegelung" },
        { "name": "helicon" },
        { "name": "heliophone" },
        { "name": "hiachi-riki" },
        { "name": "hochet" },
        { "name": "hochet a grelots" },
        { "name": "horn bugle" },
        { "name": "hornpipe" },
        { "name": "huayllaca" },
        { "name": "huqin" },
        { "name": "hwang chong tche" },
        { "name": "hwang-teih" },
        { "name": "ichigenkin" },
        { "name": "inanga" },
        { "name": "ingomba" },
        { "name": "insibi" },
        { "name": "jabisen" },
        { "name": "jagajhampa" },
        { "name": "ja-kin'rh" },
        { "name": "jaleika" },
        { "name": "jamblock" },
        { "name": "jarana" },
        { "name": "jejy voatavo" },
        { "name": "jenbe" },
        { "name": "jeu de timbre" },
        { "name": "jouhikko" },
        { "name": "ka" },
        { "name": "kabosse" },
        { "name": "kacapi" },
        { "name": "kacha-vinabossy" },
        { "name": "kachapi-vina" },
        { "name": "kagoura-fouye" },
        { "name": "kairata-vina" },
        { "name": "kalimba" },
        { "name": "kamalen koni" },
        { "name": "kamanja" },
        { "name": "kandang indien" },
        { "name": "kanih" },
        { "name": "kankangui" },
        { "name": "kanoon ou qanon" },
        { "name": "kanoun" },
        { "name": "kantele" },
        { "name": "kanyahte'ka'nowa" },
        { "name": "kao kao javanais" },
        { "name": "kara" },
        { "name": "karabid" },
        { "name": "karkabet" },
        { "name": "karna" },
        { "name": "kass" },
        { "name": "kasso" },
        { "name": "kattyauma-vina" },
        { "name": "kaval" },
        { "name": "kayamb" },
        { "name": "kazoo" },
        { "name": "kemace" },
        { "name": "kemangeh a gouz" },
        { "name": "kemangeh-roumy" },
        { "name": "kena" },
        { "name": "kesbate" },
        { "name": "kese kese" },
        { "name": "keseng keseng" },
        { "name": "ketipoeng" },
        { "name": "ketjapi" },
        { "name": "kharatala" },
        { "name": "khen" },
        { "name": "khol" },
        { "name": "khoradah" },
        { "name": "khurdra kattyauna-vina" },
        { "name": "kin" },
        { "name": "kin-kon" },
        { "name": "kinan" },
        { "name": "king" },
        { "name": "kinnari-vina" },
        { "name": "kinnery" },
        { "name": "kiringie" },
        { "name": "kissar" },
        { "name": "klaxon" },
        { "name": "klentony" },
        { "name": "koant-tse" },
        { "name": "kobza" },
        { "name": "koholo" },
        { "name": "kokiou" },
        { "name": "konkoni" },
        { "name": "kora" },
        { "name": "kotek" },
        { "name": "koto" },
        { "name": "kou" },
        { "name": "koundyeh" },
        { "name": "kousser" },
        { "name": "kpanouhoun" },
        { "name": "kpezin" },
        { "name": "kuitra" },
        { "name": "kulintang" },
        { "name": "kunjerry" },
        { "name": "langeleik " },
        { "name": "lapa" },
        { "name": "laya bansi" },
        { "name": "lira da braccio" },
        { "name": "lirone " },
        { "name": "lithophone" },
        { "name": "lituus" },
        { "name": "lo " },
        { "name": "lo kou " },
        { "name": "lokombi " },
        { "name": "loure" },
        { "name": "lu tchun" },
        { "name": "lung-tao-ty" },
        { "name": "luth" },
        { "name": "lyre" },
        { "name": "lyro-guitare" },
        { "name": "lyrone" },
        { "name": "ma-ca-doi" },
        { "name": "madiumba" },
        { "name": "magondi" },
        { "name": "magrouna" },
        { "name": "maha-mandira" },
        { "name": "mahati-vina" },
        { "name": "mainty kely" },
        { "name": "malakat" },
        { "name": "mandira" },
        { "name": "mandoline" },
        { "name": "mandoline country" },
        { "name": "mandoloncelle" },
        { "name": "mandolute" },
        { "name": "mandore" },
        { "name": "mandurria" },
        { "name": "manichordion" },
        { "name": "maracas" },
        { "name": "maravanne" },
        { "name": "marddala" },
        { "name": "marimba" },
        { "name": "marouvane" },
        { "name": "matremine" },
        { "name": "mattauphone" },
        { "name": "mayuri ou tayuc" },
        { "name": "mazhar" },
        { "name": "m'bira" },
        { "name": "medylenara" },
        { "name": "megyoung" },
        { "name": "meia-lua" },
        { "name": "mellophone" },
        { "name": "mellotron" },
        { "name": "melodica" },
        { "name": "merline" },
        { "name": "metronome" },
        { "name": "mezoued" },
        { "name": "mina-sarangi" },
        { "name": "mirliton" },
        { "name": "mizmar" },
        { "name": "mochanga" },
        { "name": "mon yu" },
        { "name": "moraharpa" },
        { "name": "morin khuur" },
        { "name": "mridang" },
        { "name": "mridangam" },
        { "name": "muselaar" },
        { "name": "musette" },
        { "name": "nacaire" },
        { "name": "nadeshvara-vina" },
        { "name": "nafir" },
        { "name": "nagara" },
        { "name": "nagelgeige" },
        { "name": "nagelharmonica" },
        { "name": "nagharats" },
        { "name": "nai" },
        { "name": "nanga" },
        { "name": "napura" },
        { "name": "nay " },
        { "name": "neo-cor" },
        { "name": "n'goni" },
        { "name": "nhac" },
        { "name": "nicolo" },
        { "name": "nihoihagi" },
        { "name": "nimfali ou ninfali" },
        { "name": "nira" },
        { "name": "nixenharfe " },
        { "name": "nkwanga " },
        { "name": "noordische balk" },
        { "name": "n'tama" },
        { "name": "nyastaranga" },
        { "name": "nyckelharpa" },
        { "name": "ocarina" },
        { "name": "ocean drum" },
        { "name": "octobasse" },
        { "name": "octoblock" },
        { "name": "olifant" },
        { "name": "ombi" },
        { "name": "omerti" },
        { "name": "omni" },
        { "name": "ondes martenot" },
        { "name": "ongo" },
        { "name": "ophicleide" },
        { "name": "organistrum" },
        { "name": "orgue" },
        { "name": "orgue de barbarie" },
        { "name": "orgue electronique" },
        { "name": "orgue numerique" },
        { "name": "orpheon" },
        { "name": "orphica" },
        { "name": "ottavino" },
        { "name": "oud" },
        { "name": "pakhawaj" },
        { "name": "pandeiro" },
        { "name": "pandereta" },
        { "name": "pandore" },
        { "name": "pandurina" },
        { "name": "patola" },
        { "name": "pedal steel" },
        { "name": "pee " },
        { "name": "pennywhistle" },
        { "name": "percuphone" },
        { "name": "phorminx" },
        { "name": "piano" },
        { "name": "piano electrique" },
        { "name": "piano a queue" },
        { "name": "piano a tangentes" },
        { "name": "piano droit" },
        { "name": "piano-forte" },
        { "name": "piano numerique" },
        { "name": "pibrock" },
        { "name": "piccolo" },
        { "name": "pipa " },
        { "name": "pipeau" },
        { "name": "planche a laver" },
        { "name": "psalterion " },
        { "name": "pung" },
        { "name": "pungi" },
        { "name": "pyrophone" },
        { "name": "qanun" },
        { "name": "qarnay " },
        { "name": "qilaut " },
        { "name": "qin" },
        { "name": "quena" },
        { "name": "quinton" },
        { "name": "rabab" },
        { "name": "rauschpfeife" },
        { "name": "ravanastron" },
        { "name": "reactable" },
        { "name": "rebec" },
        { "name": "regale" },
        { "name": "repinique" },
        { "name": "rhombe" },
        { "name": "riqq" },
        { "name": "rouler" },
        { "name": "sabar" },
        { "name": "sacqueboute" },
        { "name": "sagat" },
        { "name": "salamouri" },
        { "name": "salpinx" },
        { "name": "sambucca" },
        { "name": "san-heen" },
        { "name": "sanai" },
        { "name": "sange" },
        { "name": "santir" },
        { "name": "santour" },
        { "name": "sanyogi" },
        { "name": "sanza" },
        { "name": "sarala-bensi" },
        { "name": "sarangi" },
        { "name": "sarciros" },
        { "name": "sarod" },
        { "name": "sarou" },
        { "name": "sarrussophone" },
        { "name": "satara" },
        { "name": "sato" },
        { "name": "saung" },
        { "name": "saw dorang" },
        { "name": "saw-duang" },
        { "name": "saw-tai" },
        { "name": "saxhorn" },
        { "name": "saxophone " },
        { "name": "saxophone alto" },
        { "name": "saxophone baryton" },
        { "name": "saxophone basse" },
        { "name": "saxophone contrebasse" },
        { "name": "saxophone sopranino" },
        { "name": "saxophone piccolo" },
        { "name": "saxophone soprano" },
        { "name": "saxophone tenor" },
        { "name": "saxotromba" },
        { "name": "saz" },
        { "name": "scabellum" },
        { "name": "schalmey" },
        { "name": "schiguene" },
        { "name": "schiti-gekkin " },
        { "name": "schlagzither" },
        { "name": "scho" },
        { "name": "schofar" },
        { "name": "schoko" },
        { "name": "schounga" },
        { "name": "scie musicale" },
        { "name": "sciotang" },
        { "name": "seaou-po" },
        { "name": "selantan" },
        { "name": "selompret" },
        { "name": "serdam" },
        { "name": "serinette" },
        { "name": "serpent" },
        { "name": "setar" },
        { "name": "shakuhachi" },
        { "name": "shamisen" },
        { "name": "sharadiya-vina" },
        { "name": "shekere" },
        { "name": "shehnai" },
        { "name": "sheng" },
        { "name": "shophar" },
        { "name": "showktica-vina" },
        { "name": "shuang-kin" },
        { "name": "siao" },
        { "name": "sifflet" },
        { "name": "sigou-mbarva" },
        { "name": "sigou-nihou" },
        { "name": "siku" },
        { "name": "silbote" },
        { "name": "sinbi" },
        { "name": "siyotantka" },
        { "name": "sira " },
        { "name": "sistre" },
        { "name": "sitar" },
        { "name": "sodina" },
        { "name": "sody" },
        { "name": "soly" },
        { "name": "sona" },
        { "name": "sonaja" },
        { "name": "sopilka" },
        { "name": "sorna" },
        { "name": "soubassophone" },
        { "name": "soudzou" },
        { "name": "souffarrah" },
        { "name": "soug" },
        { "name": "souma-koto" },
        { "name": "soung-king" },
        { "name": "sounnaia" },
        { "name": "souqqarah" },
        { "name": "sourdine" },
        { "name": "sousounou" },
        { "name": "spitzharfe" },
        { "name": "sringa" },
        { "name": "sruti-vina" },
        { "name": "stamentien-pfeiffe" },
        { "name": "steel-drum" },
        { "name": "stick" },
        { "name": "stock-horn" },
        { "name": "stopf-trumpet" },
        { "name": "streich-zither" },
        { "name": "stretch machine" },
        { "name": "suka" },
        { "name": "suling " },
        { "name": "suona" },
        { "name": "sur-bahara" },
        { "name": "sur-vahara" },
        { "name": "sur-vina" },
        { "name": "surdo" },
        { "name": "swedish bagpipe" },
        { "name": "synthetiseur" },
        { "name": "syntophone" },
        { "name": "sze-hou-hsien" },
        { "name": "ta huang hou kin" },
        { "name": "taakan" },
        { "name": "taarija" },
        { "name": "tabla" },
        { "name": "tablat" },
        { "name": "taiko" },
        { "name": "taisene" },
        { "name": "taki-koto" },
        { "name": "talain" },
        { "name": "tam-tam" },
        { "name": "tama" },
        { "name": "tambin" },
        { "name": "tamborim" },
        { "name": "tambour" },
        { "name": "tambourin" },
        { "name": "tambur" },
        { "name": "tan-tan" },
        { "name": "tao-kou" },
        { "name": "tarogato" },
        { "name": "tapan" },
        { "name": "tar" },
        { "name": "tarambouka" },
        { "name": "tarole" },
        { "name": "tarqa" },
        { "name": "tasa" },
        { "name": "tashepoto" },
        { "name": "tatchoota" },
        { "name": "tawaya" },
        { "name": "tbal" },
        { "name": "tchang-kou" },
        { "name": "tche" },
        { "name": "tchengue" },
        { "name": "tchogor" },
        { "name": "tchong" },
        { "name": "tchong-tou" },
        { "name": "tchou" },
        { "name": "te-tchong" },
        { "name": "tebashoul" },
        { "name": "tebilats" },
        { "name": "tebloun" },
        { "name": "telharmonium" },
        { "name": "tembour" },
        { "name": "tenora" },
        { "name": "terab-enguiz" },
        { "name": "terpodion" },
        { "name": "terr" },
        { "name": "tet-jer" },
        { "name": "thar" },
        { "name": "thari" },
        { "name": "theorbe" },
        { "name": "theremine" },
        { "name": "thumgo-tuapan" },
        { "name": "thurnerhorn" },
        { "name": "ti-kin" },
        { "name": "tien-kou" },
        { "name": "tilinca" },
        { "name": "timba" },
        { "name": "timbale" },
        { "name": "timbales" },
        { "name": "timple" },
        { "name": "tin whistle" },
        { "name": "tiple" },
        { "name": "tje-tje" },
        { "name": "tohona" },
        { "name": "tombah" },
        { "name": "tombak" },
        { "name": "tom" },
        { "name": "to rung " },
        { "name": "toumourah" },
        { "name": "tournebout" },
        { "name": "tourti" },
        { "name": "toutsoumi" },
        { "name": "trawanga" },
        { "name": "tres" },
        { "name": "triangle" },
        { "name": "tritantri-vina" },
        { "name": "tritare" },
        { "name": "trombone" },
        { "name": "troccola" },
        { "name": "trompe de chasse" },
        { "name": "trompette" },
        { "name": "trompette de poche" },
        { "name": "trompette marine" },
        { "name": "trompette piccolo" },
        { "name": "tseng" },
        { "name": "tsikadraha" },
        { "name": "tsou-kou" },
        { "name": "tsou toung hou-kin" },
        { "name": "tsouma-koto" },
        { "name": "tsouzoumi" },
        { "name": "tuba" },
        { "name": "tuba corva" },
        { "name": "tuba wagnerien" },
        { "name": "tubilattes" },
        { "name": "tubri" },
        { "name": "tubular bells" },
        { "name": "tumburu-vina" },
        { "name": "turi" },
        { "name": "turr" },
        { "name": "txalaparta" },
        { "name": "txanbela" },
        { "name": "txirula" },
        { "name": "txistu" },
        { "name": "ty" },
        { "name": "tympanon" },
        { "name": "ukulele" },
        { "name": "udu" },
        { "name": "venu" },
        { "name": "veuze" },
        { "name": "vibraphone" },
        { "name": "vibraslap" },
        { "name": "viele" },
        { "name": "vielle a roue" },
        { "name": "vihuela" },
        { "name": "vina" },
        { "name": "viole" },
        { "name": "viole d'amour" },
        { "name": "viole de gambe" },
        { "name": "violon" },
        { "name": "violon a pavillon" },
        { "name": "violoncelle" },
        { "name": "violone" },
        { "name": "virginal" },
        { "name": "voix" },
        { "name": "vuvuzela" },
        { "name": "wakrapuku" },
        { "name": "waterphone" },
        { "name": "wood-block" },
        { "name": "xaphoon" },
        { "name": "xiao" },
        { "name": "xun" },
        { "name": "xylophone" },
        { "name": "yabara" },
        { "name": "yang" },
        { "name": "yueqin" },
        { "name": "zampona" },
        { "name": "zarb " },
        { "name": "zurna" }],

        "fruit": [{ "name": "abricot" },
        { "name": "acerola" },
        { "name": "hassaku" },
        { "name": "ugli" },
        { "name": "zatte" },
        { "name": "airelle" },
        { "name": "alkekenge" },
        { "name": "amande" },
        { "name": "amelanche" },
        { "name": "ananas" },
        { "name": "ananas" },
        { "name": "arbouse" },
        { "name": "asimine" },
        { "name": "aubergine" },
        { "name": "avocat" },
        { "name": "avocat" },
        { "name": "avocat" },
        { "name": "banane" },
        { "name": "banane" },
        { "name": "barbadine" },
        { "name": "bergamote" },
        { "name": "bigarade" },
        { "name": "bigarade" },
        { "name": "brugnon" },
        { "name": "cacao" },
        { "name": "cachiman" },
        { "name": "caimite" },
        { "name": "canneberge" },
        { "name": "carambole" },
        { "name": "cassis" },
        { "name": "cerise" },
        { "name": "cerise de cayenne" },
        { "name": "chataigne" },
        { "name": "chayotte" },
        { "name": "cherimole" },
        { "name": "cherimoya" },
        { "name": "cherimoya" },
        { "name": "chinois" },
        { "name": "citron" },
        { "name": "citron vert" },
        { "name": "citrouille" },
        { "name": "clementine" },
        { "name": "coing" },
        { "name": "combava" },
        { "name": "concombre" },
        { "name": "cornichon" },
        { "name": "cornouiller du canada" },
        { "name": "corossol" },
        { "name": "courge" },
        { "name": "courge musquee" },
        { "name": "courgette" },
        { "name": "cucamelon" },
        { "name": "cynorrhodon" },
        { "name": "datte" },
        { "name": "durian" },
        { "name": "epine-vinette" },
        { "name": "fe'i" },
        { "name": "feijoa" },
        { "name": "figue" },
        { "name": "figue de barbarie" },
        { "name": "fraise" },
        { "name": "framboise" },
        { "name": "fruit de la passion" },
        { "name": "fruit de la passion" },
        { "name": "fruit-a-pain" },
        { "name": "girembelle" },
        { "name": "gombo" },
        { "name": "goyave" },
        { "name": "goyave" },
        { "name": "grenade" },
        { "name": "grenadelle" },
        { "name": "grenadille" },
        { "name": "grenadille sucree" },
        { "name": "griotte" },
        { "name": "groseille" },
        { "name": "icaque" },
        { "name": "jacque" },
        { "name": "jambose rouge" },
        { "name": "jujube" },
        { "name": "kaki" },
        { "name": "kiwai" },
        { "name": "kiwano" },
        { "name": "kiwi" },
        { "name": "kumquat" },
        { "name": "les passiflores " },
        { "name": "lime" },
        { "name": "litchi" },
        { "name": "litchi" },
        { "name": "longane" },
        { "name": "mandarine" },
        { "name": "mangoustan" },
        { "name": "mangue" },
        { "name": "maracudja" },
        { "name": "margose" },
        { "name": "marron" },
        { "name": "melon" },
        { "name": "melon" },
        { "name": "mirabelle" },
        { "name": "mombin" },
        { "name": "mure" },
        { "name": "myrobolan" },
        { "name": "myrte" },
        { "name": "myrtille" },
        { "name": "nefle" },
        { "name": "nefle du japon" },
        { "name": "nefle du japon" },
        { "name": "neflier des indes" },
        { "name": "noisette" },
        { "name": "noix" },
        { "name": "noix de cajou" },
        { "name": "noix de coco" },
        { "name": "noix de muscade" },
        { "name": "olive" },
        { "name": "orange" },
        { "name": "orange amere" },
        { "name": "pain de singe" },
        { "name": "pamplemousse" },
        { "name": "papaye" },
        { "name": "pasteque" },
        { "name": "patisson" },
        { "name": "peche" },
        { "name": "pepino" },
        { "name": "physalis" },
        { "name": "piment" },
        { "name": "pistache" },
        { "name": "pitaya" },
        { "name": "plaquebiere" },
        { "name": "poire" },
        { "name": "poivron" },
        { "name": "pomelos" },
        { "name": "pomme" },
        { "name": "pomme de cajou" },
        { "name": "pomme de lait" },
        { "name": "pomme de lait" },
        { "name": "pomme liane" },
        { "name": "potiron" },
        { "name": "prune" },
        { "name": "prune de cythere" },
        { "name": "pruneau" },
        { "name": "quenette" },
        { "name": "quetsche" },
        { "name": "raisin" },
        { "name": "ramboutan" },
        { "name": "salak" },
        { "name": "sapote" },
        { "name": "sapotille" },
        { "name": "tamarillo" },
        { "name": "tamarin" },
        { "name": "tamarin des indes " },
        { "name": "tamarin d'inde" },
        { "name": "taxo" },
        { "name": "tomate" },
        { "name": "yuzu" }],

        "capital": [{ "name": "abou dabi" },
        { "name": "abuja" },
        { "name": "accra" },
        { "name": "achgabat" },
        { "name": "addis-abeba" },
        { "name": "alger" },
        { "name": "alofi" },
        { "name": "amman" },
        { "name": "amsterdam" },
        { "name": "andorre-la-vieille" },
        { "name": "ankara" },
        { "name": "antananarivo" },
        { "name": "apia" },
        { "name": "asmara" },
        { "name": "astana" },
        { "name": "asuncion" },
        { "name": "athenes" },
        { "name": "avarua" },
        { "name": "bagdad" },
        { "name": "bakou" },
        { "name": "bamako" },
        { "name": "bandar seri begawan" },
        { "name": "bangkok" },
        { "name": "bangui" },
        { "name": "banjul" },
        { "name": "basseterre" },
        { "name": "belgrade" },
        { "name": "belmopan" },
        { "name": "berlin" },
        { "name": "berne" },
        { "name": "beyrouth" },
        { "name": "bichkek" },
        { "name": "bissau" },
        { "name": "bloemfontein" },
        { "name": "bogota" },
        { "name": "brasilia" },
        { "name": "bratislava" },
        { "name": "brazzaville" },
        { "name": "bridgetown" },
        { "name": "bruxelles" },
        { "name": "bucarest" },
        { "name": "budapest" },
        { "name": "buenos aires" },
        { "name": "bujumbura" },
        { "name": "le caire" },
        { "name": "canberra" },
        { "name": "le cap" },
        { "name": "caracas" },
        { "name": "castries" },
        { "name": "chisinau" },
        { "name": "sri jayawardenapura" },
        { "name": "conakry" },
        { "name": "copenhague" },
        { "name": "dakar" },
        { "name": "damas" },
        { "name": "dar es salam" },
        { "name": "delap-uliga-darrit" },
        { "name": "dacca" },
        { "name": "dili" },
        { "name": "djibouti" },
        { "name": "djouba" },
        { "name": "dodoma" },
        { "name": "doha" },
        { "name": "douchanbe" },
        { "name": "dublin" },
        { "name": "erevan" },
        { "name": "freetown" },
        { "name": "funafuti" },
        { "name": "gaborone" },
        { "name": "georgetown" },
        { "name": "guatemala" },
        { "name": "hanoi" },
        { "name": "harare" },
        { "name": "la havane" },
        { "name": "la haye" },
        { "name": "helsinki" },
        { "name": "honiara" },
        { "name": "islamabad" },
        { "name": "jakarta" },
        { "name": "jerusalem" },
        { "name": "jerusalem-est" },
        { "name": "kaboul" },
        { "name": "kampala" },
        { "name": "katmandou" },
        { "name": "khartoum" },
        { "name": "kiev" },
        { "name": "kigali" },
        { "name": "kingston" },
        { "name": "kingstown" },
        { "name": "kinshasa" },
        { "name": "melekeok" },
        { "name": "koweit" },
        { "name": "kuala lumpur" },
        { "name": "libreville" },
        { "name": "lilongwe" },
        { "name": "lima" },
        { "name": "lisbonne" },
        { "name": "ljubljana" },
        { "name": "lome" },
        { "name": "londres" },
        { "name": "luanda" },
        { "name": "lusaka" },
        { "name": "luxembourg" },
        { "name": "madrid" },
        { "name": "malabo" },
        { "name": "male" },
        { "name": "managua" },
        { "name": "manama" },
        { "name": "manille" },
        { "name": "maputo" },
        { "name": "mascate" },
        { "name": "maseru" },
        { "name": "mbabane" },
        { "name": "mexico" },
        { "name": "minsk" },
        { "name": "mogadiscio" },
        { "name": "monaco" },
        { "name": "monrovia" },
        { "name": "montevideo" },
        { "name": "moroni" },
        { "name": "moscou" },
        { "name": "nairobi" },
        { "name": "nassau" },
        { "name": "naypyidaw" },
        { "name": "n'djamena" },
        { "name": "new delhi" },
        { "name": "niamey" },
        { "name": "nicosie" },
        { "name": "nouakchott" },
        { "name": "nuku'alofa" },
        { "name": "oranjestad" },
        { "name": "oslo" },
        { "name": "ottawa" },
        { "name": "ouagadougou" },
        { "name": "oulan-bator" },
        { "name": "palikir" },
        { "name": "panama" },
        { "name": "paramaribo" },
        { "name": "paris" },
        { "name": "la paz" },
        { "name": "pekin" },
        { "name": "phnom penh" },
        { "name": "podgorica" },
        { "name": "port moresby" },
        { "name": "port-au-prince" },
        { "name": "port-d'espagne" },
        { "name": "port-louis" },
        { "name": "porto-novo" },
        { "name": "port-vila" },
        { "name": "prague" },
        { "name": "praia" },
        { "name": "pretoria" },
        { "name": "putrajaya" },
        { "name": "pyongyang" },
        { "name": "quito" },
        { "name": "rabat" },
        { "name": "ramallah" },
        { "name": "reykjavik" },
        { "name": "riga" },
        { "name": "riyad" },
        { "name": "rome" },
        { "name": "roseau" },
        { "name": "saint john's" },
        { "name": "saint-domingue" },
        { "name": "saint-georges" },
        { "name": "saint-marin" },
        { "name": "san jose" },
        { "name": "san salvador" },
        { "name": "sanaa" },
        { "name": "santiago" },
        { "name": "sao tome" },
        { "name": "sarajevo" },
        { "name": "seoul" },
        { "name": "singapour" },
        { "name": "skopje" },
        { "name": "sofia" },
        { "name": "stockholm" },
        { "name": "sucre" },
        { "name": "suva" },
        { "name": "tachkent" },
        { "name": "tallinn" },
        { "name": "tarawa-sud" },
        { "name": "tbilissi" },
        { "name": "tegucigalpa" },
        { "name": "teheran" },
        { "name": "tel aviv-jaffa" },
        { "name": "thimphou" },
        { "name": "tirana" },
        { "name": "tokyo" },
        { "name": "tripoli" },
        { "name": "tunis" },
        { "name": "vaduz" },
        { "name": "la valette" },
        { "name": "varsovie" },
        { "name": "cite du vatican" },
        { "name": "victoria" },
        { "name": "vienne" },
        { "name": "vientiane" },
        { "name": "vilnius" },
        { "name": "washington d.c." },
        { "name": "wellington" },
        { "name": "windhoek" },
        { "name": "yamoussoukro" },
        { "name": "yaounde" },
        { "name": "yaren" },
        { "name": "zagreb" }],

        "fleur": [{ "name": "abutilon" },
        { "name": "acacia" },
        { "name": "acacia rose" },
        { "name": "acacia" },
        { "name": "acanthe" },
        { "name": "achillee " },
        { "name": "Kalimeris" },
        { "name": "Quinoa" },
        { "name": "Utricularia" },
        { "name": "Wattakaka" },
        { "name": "Yucca" },
        { "name": "achille millefeuille" },
        { "name": "aconit" },
        { "name": "adonis" },
        { "name": "agapanthe" },
        { "name": "aigremoine" },
        { "name": "airelle" },
        { "name": "ajonc" },
        { "name": "alcee" },
        { "name": "allium" },
        { "name": "aloes" },
        { "name": "alstroemere" },
        { "name": "alysson maritime" },
        { "name": "amandier" },
        { "name": "amarante" },
        { "name": "amarante queue-de-renard " },
        { "name": "amaryllis" },
        { "name": "ammi " },
        { "name": "amour en cage" },
        { "name": "anagallis" },
        { "name": "ancolie" },
        { "name": "anemone " },
        { "name": "anthemis " },
        { "name": "aster " },
        { "name": "astragale " },
        { "name": "aubepine" },
        { "name": "azalee" },
        { "name": "balsamine " },
        { "name": "barbotine " },
        { "name": "basilic " },
        { "name": "begonia" },
        { "name": "belle dame " },
        { "name": "bleuet " },
        { "name": "bouton d'or " },
        { "name": "briza " },
        { "name": "bruyere  " },
        { "name": "buglosse " },
        { "name": "cactus " },
        { "name": "camelia " },
        { "name": "blanc " },
        { "name": "rouge " },
        { "name": "camomille " },
        { "name": "campanule " },
        { "name": "capucine " },
        { "name": "cedre " },
        { "name": "ceibo " },
        { "name": "centauree " },
        { "name": "char de venus " },
        { "name": "chataignier " },
        { "name": "cerisier " },
        { "name": "chevrefeuille " },
        { "name": "chrysantheme " },
        { "name": "citronnier " },
        { "name": "clematite " },
        { "name": "cognassier " },
        { "name": "coquelicot " },
        { "name": "corbeille d'argent " },
        { "name": "coreopsis " },
        { "name": "cornouiller " },
        { "name": "couronne imperiale " },
        { "name": "cristalline " },
        { "name": "crocus " },
        { "name": "cyclamen" },
        { "name": "cypres " },
        { "name": "dahlia " },
        { "name": "digitale " },
        { "name": "eglantine " },
        { "name": "erable " },
        { "name": "fenouil " },
        { "name": "figuier " },
        { "name": "fougere " },
        { "name": "fraisier " },
        { "name": "freesia " },
        { "name": "frene" },
        { "name": "fuchsia" },
        { "name": "genevrier" },
        { "name": "gentiane " },
        { "name": "geranium " },
        { "name": "gerbe d'or" },
        { "name": "gerbera" },
        { "name": "giroflee " },
        { "name": "giroflee des murailles" },
        { "name": "glaieul" },
        { "name": "glycine " },
        { "name": "grenadier " },
        { "name": "groseille a maquereau " },
        { "name": "gueule de loup " },
        { "name": "gui " },
        { "name": "heliotrope" },
        { "name": "herbe " },
        { "name": "hetre" },
        { "name": "hortensia" },
        { "name": "houx " },
        { "name": "if " },
        { "name": "iris " },
        { "name": "jacinthe " },
        { "name": "pourpre " },
        { "name": "sauvage " },
        { "name": "jasmin " },
        { "name": "jasmin-trompette" },
        { "name": "jonquille " },
        { "name": "kalmie" },
        { "name": "laitue " },
        { "name": "laurier " },
        { "name": "laurier-rose " },
        { "name": "lavande " },
        { "name": "lycoris radiata " },
        { "name": "lierre" },
        { "name": "lilas commun " },
        { "name": "en general" },
        { "name": "lin" },
        { "name": "liseron" },
        { "name": "pourpre" },
        { "name": "lotus" },
        { "name": "lys " },
        { "name": "magnolia " },
        { "name": "marguerite " },
        { "name": "marjolaine " },
        { "name": "menthe " },
        { "name": "menthe poivree " },
        { "name": "menthe verte " },
        { "name": "millepertuis " },
        { "name": "mimosa " },
        { "name": "mouron " },
        { "name": "mouron des oiseaux " },
        { "name": "muguet " },
        { "name": "muscaris " },
        { "name": "myosotis " },
        { "name": "myrte" },
        { "name": "narcisse " },
        { "name": "nemophile " },
        { "name": "nenuphar" },
        { "name": "noisetier" },
        { "name": "œillet " },
        { "name": "œillet de montagne " },
        { "name": "œillet diapre" },
        { "name": "olivier " },
        { "name": "oranger " },
        { "name": "orchidee " },
        { "name": "blanche " },
        { "name": "jaune " },
        { "name": "rose" },
        { "name": "rouge " },
        { "name": "oreille d'ours " },
        { "name": "orme" },
        { "name": "ortie" },
        { "name": "oxalide" },
        { "name": "blanche" },
        { "name": "palmier" },
        { "name": "passiflore" },
        { "name": "patience" },
        { "name": "pavot" },
        { "name": "ecarlate" },
        { "name": "pavot de tournefort" },
        { "name": "pecher " },
        { "name": "pelargonium " },
        { "name": "pensee " },
        { "name": "perce-neige " },
        { "name": "pervenche " },
        { "name": "petunia " },
        { "name": "phlox" },
        { "name": "pied d'alouette " },
        { "name": "pin " },
        { "name": "pissenlit " },
        { "name": "pivoine " },
        { "name": "plante verte " },
        { "name": "poirier " },
        { "name": "pois de senteur" },
        { "name": "pommier" },
        { "name": "primevere " },
        { "name": "raisin " },
        { "name": "raisin de loup " },
        { "name": "raisin sauvage " },
        { "name": "renoncule " },
        { "name": "reseda " },
        { "name": "rhododendron " },
        { "name": "romarin " },
        { "name": "rose " },
        { "name": "blanche " },
        { "name": "bleue " },
        { "name": "jaune " },
        { "name": "rose " },
        { "name": "rouge " },
        { "name": "rose de noel " },
        { "name": "roseau " },
        { "name": "fendu" },
        { "name": "roquette" },
        { "name": "rue" },
        { "name": "sabot de venus" },
        { "name": "safran" },
        { "name": "sauge" },
        { "name": "saule" },
        { "name": "saxifrage" },
        { "name": "scirpe" },
        { "name": "seringa" },
        { "name": "souci " },
        { "name": "stramoine" },
        { "name": "sycomore" },
        { "name": "thuya" },
        { "name": "thym" },
        { "name": "tigridia" },
        { "name": "tradescantia" },
        { "name": "trefle" },
        { "name": "trefle d'irlande" },
        { "name": "trefle rouge" },
        { "name": "trefle blanc" },
        { "name": "tubereuse" },
        { "name": "tulipe" },
        { "name": "tulipe diapree " },
        { "name": "tulipier" },
        { "name": "valeriane" },
        { "name": "veronique" },
        { "name": "verveine" },
        { "name": "blanche" },
        { "name": "ecarlate" },
        { "name": "vigne " },
        { "name": "vigne vierge" },
        { "name": "violette " },
        { "name": "en general" },
        { "name": "volubilis" },
        { "name": "volubilis mineur" },
        { "name": "volubilis majeur" },
        { "name": "xanthium" },
        { "name": "zephyranthes" },
        { "name": "zinnia" }]
    }
};
	
		var score = 0;
        var latitudeUser = 0;
        var longitudeUser = 0;

        if (navigator.geolocation)
        {
            navigator.geolocation.getCurrentPosition(showPosition);
        } 

        function showPosition(position)
        {
            latitudeUser = position.coords.latitude; 
            longitudeUser = position.coords.longitude;
        }

        function randomize() {

            $("#answer").val("");
            // clear input when enter
            var input = document.getElementById("answer");
            input.focus();

            var mycategories = ['pays', 'voiture', 'couleur', 'mammiferes',
                'instrument', 'fruit', 'capital', 'fleur'];
            var category = mycategories[Math.floor(Math.random() * mycategories.length)];
            console.log(category.toString())
            document.getElementById("categorie").innerHTML=category.toString();
            setCategory(category.toString())
			

            //random letter
            document.getElementById("lettre").innerText= String.fromCharCode(97 + (Math.random() * 26)).toUpperCase();
            console.log(document.getElementById("lettre").value)

            resetTimer();
        }
		
		
		
		
		

        randomize();
		
		
	

        // clear input when enter
        var input = document.getElementById("answer");
		input.focus();


        // Execute a function when the user releases a key on the keyboard
        input.addEventListener("keyup", function(event) {
            // Cancel the default action, if needed
            event.preventDefault();
            // Number 13 is the "Enter" key on the keyboard
            if (event.keyCode === 13) {
                // Trigger the button element with a click
                document.getElementById("btn").click();
                input.value = '';
            }
        });
		
		


        var response;
		//Get the correct possibilities for a categories
        function setCategory(categories) {
            if(categories==="pays"){
                response = json.categorie.pays;

                if (document.getElementById("lettre").value == "x" || document.getElementById("lettre").value == "u")
                {
                    randomize();
                }
            }
            if(categories==="couleur"){
                response =json.categorie.couleur;
            }
            if(categories==="voiture"){
                response =json.categorie.voiture;
            }
            if(categories==="mammiferes"){
                response =json.categorie.mammiferes;
            }
            if(categories==="instrument"){
                response =json.categorie.instrument;
            }
            if(categories==="fruit"){
                response =json.categorie.fruit;
            }
            if(categories==="capital"){
                response =json.categorie.capital;
            }
            if(categories==="fleur"){
                response =json.categorie.fleur;
            }
        }

		
		
		
		
		//Check if the answer is valide
        $("#btn").click( function(){

            var answer = document.getElementById('answer').value;
            var flag = false;

            console.log("checking ...");

            $.each(response, function (i, v)
            {
                console.log(v.name.toString().toLowerCase().trim() + " = " + answer.toString().toLowerCase().trim());

                if(answer.toString().charAt(0,1).toLowerCase()!=document.getElementById('lettre').innerText.toString().trim().toLowerCase()){
					
					//Partie terminé , ajout du score dans la db
                    flag = false;
                    return false;
                }
				
                if (v.name.toString().toLowerCase().trim() == answer.toString().toLowerCase().trim()) {
					
					//Ajouter le point
                    flag = true;
                    score += flagTimer ;
					document.getElementById("score").innerHTML=score.toString();
                    return false;
                }

               
            })

            if(flag)
            {
                console.log("randomize");
                randomize();
            }   
            else
            {
                console.log("else");
                flagTimer = 0;
            }
                
			
        })

        function endGame() {

            firebase.database().ref('users/' + uid).once('value').then(function (snapshot) {

               
                if (snapshot.val() != null)
                    firebaseOldScore = snapshot.val().highestScore;
                else
                    firebaseOldScore = 0;


                $("#precedentScore").html(firebaseOldScore);

                if (score > firebaseOldScore)
                {
                    firebase.database().ref('users/' + uid).set({
                        email: email,
                        highestScore: score,
                        latitude: latitudeUser,
                        longitude: longitudeUser
                    });
                }
                else if (firebaseOldScore == null)
                {
                    firebase.database().ref('users/' + uid).set({
                        email: email,
                        highestScore: score,
                        latitude: latitudeUser,
                        longitude: longitudeUser
                    });
                }

            })

            var audio = $("#audio");

            audio.remove();

            $("#scoreView").html(score);

            $('#modal2').modal('open');
        }
		
		

		$("#next").click( function(){
            randomize();
            $("#next").addClass("disabled");

            // clear input when enter
            var input = document.getElementById("answer");
            input.focus();
		})
		
	
		
		 $("#cheat").click( function(){

            $.each(response, function(i, v) {
				console.log((v.name.toString().toLowerCase())+" = "+document.getElementById('lettre').innerText.toString().trim().toLowerCase());
                if(v.name.toString().charAt(0,1).toLowerCase()==document.getElementById('lettre').innerText.toString().trim().toLowerCase()){
                    $("#answer").val(v.name.toString());
                    return false;
                }
             })

            $("#cheat").addClass("disabled");

            // clear input when enter
            var input = document.getElementById("answer");
            input.focus();

        })
		
		//});



